# Generated by Django 5.1.5 on 2025-01-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["name"],
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
            },
        ),
        migrations.RemoveField(
            model_name="post",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="post",
            name="was_publication",
        ),
        migrations.AddField(
            model_name="post",
            name="is_public",
            field=models.BooleanField(
                default=True,
                help_text="Укажите, доступен ли пост для просмотра",
                verbose_name="Признак публикации",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Вставьте изображение для поста",
                null=True,
                upload_to="posts/",
                verbose_name="Превью",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="views_counter",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Количество просмотров поста",
                verbose_name="Количество просмотров",
            ),
        ),
    ]
