# Generated by Django 5.1.5 on 2025-01-28 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_options_remove_post_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime.now,
                editable=False,
                help_text="Дата и время создания поста",
                verbose_name="Дата создания",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime.now,
                editable=False,
                help_text="Дата и время последнего обновления поста",
                verbose_name="Дата обновления",
            ),
        ),
    ]
