# Generated by Django 5.1.5 on 2025-01-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_created_at_post_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Дата и время создания поста",
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Дата и время последнего обновления поста",
                verbose_name="Дата обновления",
            ),
        ),
    ]
