# Generated by Django 5.1.3 on 2025-01-21 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_category_alter_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="was_publication",
            field=models.BooleanField(default=True, verbose_name="Опубликован ли"),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="category",
                to="catalog.category",
                verbose_name="Наименование категории",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateField(blank=True, null=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="product/image",
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Наименование"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.CharField(max_length=100, verbose_name="Цена"),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата последнего изменения"
            ),
        ),
    ]
