# Generated by Django 5.1.5 on 2025-01-28 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_product_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime.now,
                editable=False,
                help_text="Дата и время создания товара",
                verbose_name="Дата создания",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime.now,
                editable=False,
                help_text="Дата и время последнего обновления",
                verbose_name="Дата обновления",
            ),
        ),
    ]
